# Site settings
title: Liberale M채nner
header-img: img/home-bg.jpg
email: 101.154706@germanynet.de
copyright_name: Liberale M채nner
description: "Gleichberechtigung - auch f체r M채nner"
baseurl: "/www.liberale-maenner.net"
url: "http://www.liberale-maenner.net"
twitter_username: liberalemaenner
github_username:  ontore
facebook_username:  liberalemaenner
email_username:  101.154706@germanynet.de
# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
